FROM archlinux:latest
RUN pacman -Syu --noconfirm && pacman -S --noconfirm \
    base-devel \
    fftw \
    gcc \
    git \
    libnotify \
    libpulse \
    libusb \
    lsb-release \
    qt5-base \
    qt5-serialport \
    qt5-tools \
    && (yes | pacman -Scc)

COPY build.pacman /build.sh
ENTRYPOINT /build.sh

