name: CI Build

on:
  push:
    branches: [ actions_tests ]

jobs:
  mac_build:
    runs-on: macOS-11.0
    name: macOS 11 Big Sur Build
    env:
      QTDIR: /usr/local/opt/qt
      BINDIR: Software/bin
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Pre-build setup
        run: |
          set -x
          brew update
          brew install qt5
          $QTDIR/bin/qmake -v
          clang -v
          gcc -v
          sysctl machdep.cpu
      - name: Build
        run: |
          export PATH=$QTDIR/bin:$PATH
          export VERSION=`cat Software/VERSION`
          cd Software
          ./update_locales.sh
          qmake -r
          make
      - name: Package DMG
        run: $QTDIR/bin/macdeployqt $BINDIR/Prismatik.app -dmg
      - name: Check DMG
        env:
          ATTACHOUT: ${{ runner.temp }}/attach
        run: |
          set -x
          cd $BINDIR
          ls
          hdiutil attach Prismatik.dmg > $ATTACHOUT
          cat $ATTACHOUT
          VOLUME=`cat $ATTACHOUT | grep -oE '/Volumes/[^[:space:]]+'`
          [ -e "$VOLUME" ]
          ls $VOLUME/Prismatik.app
          otool -L $VOLUME/Prismatik.app/Contents/MacOS/Prismatik
          otool -L $VOLUME/Prismatik.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
          hdiutil detach $VOLUME
      - name: Upload DMG
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Prismatik.dmg
          path: ${{ env.BINDIR }}/Prismatik.dmg
