name: CI Build

on:
  push:
    branches: [ actions_tests ]

jobs:
  mac_build:
    runs-on: macOS-11.0
    name: macOS 11 Big Sur Build
    env:
      QTDIR: /usr/local/opt/qt
      BINDIR: Software/bin
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Pre-build setup
        run: |
          set -x
          brew update
          brew install qt5
          $QTDIR/bin/qmake -v
          clang -v
          gcc -v
      - name: Build
        run: |
          export PATH=$QTDIR/bin:$PATH
          export VERSION=`cat Software/VERSION`
          cd Software
          ./update_locales.sh
          qmake -r
          make
      - name: Package DMG
        run: $QTDIR/bin/macdeployqt $BINDIR/Prismatik.app -dmg
      - name: Check DMG
        run: |
          set -x
          ls $BINDIR
          hdiutil attach $BINDIR/Prismatik.dmg
          ls /Volumes/bin:Prismatik/Prismatik.app
          otool -L /Volumes/bin:Prismatik/Prismatik.app/Contents/MacOS/Prismatik
          otool -L /Volumes/bin:Prismatik/Prismatik.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
          hdiutil detach /Volumes/bin:Prismatik
